# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "newsletter-app"
client_id = "5378891fcefda5c494bb81678929549f"
application_url = "https://nintendo-reel-straight-airports.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://nintendo-reel-straight-airports.trycloudflare.com/auth/callback",
  "https://nintendo-reel-straight-airports.trycloudflare.com/auth/shopify/callback",
  "https://nintendo-reel-straight-airports.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-7fd47dc3.myshopify.com"
